#!/usr/bin/env bash
#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# This script provides information about specified subdomains.

# The function retrieves and displays details about a given subdomain
domain_information () {
    # Utilize dig to query DNS and extract relevant subdomain information
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')

    # Print details such as subdomain, DNS record type, and its destination
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check the number of command-line arguments
if [ "$#" == 1 ]; then
    # Display information for specific default subdomains
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    # Display information for the specified subdomain
    domain_information "$1" "$2"
fi
