#!/usr/bin/env bash
# Install nginx on  web-01 server
# Nginx  listening on port 80
# When querying Nginx at its '/' root  with a GET requesting a page
# using curl, it must return a page that contains the string Holberton School

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
