#!/usr/bin/env bash
# Nginx Configuration Script with Custom Header
# This script configures Nginx on web-01 and web-02 to include a custom header in HTTP responses.

# Get the hostname
var=$(hostname)

# Define strings for configuration modifications
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

# Update package information
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create a basic HTML file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create a directory for custom HTML
mkdir -p /var/www/html

# Create a custom 404 HTML file
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Modify Nginx default configuration to include custom settings
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx starti
